/**
 * Wk9 PLANv2 G2 — Macro resolver.
 *
 * Resolves `{{...}}` macros in prompt strings to scene-appropriate values.
 * Supported tokens (per PLANv2 §wk9 acceptance):
 *
 *   {{char}}     → character name
 *   {{user}}     → active persona name OR user displayName (fallback)
 *   {{persona}}  → active persona name (empty string when unset)
 *   {{time}}     → HH:mm in scene zone (or system local when unset)
 *   {{date}}     → ISO-ish "YYYY-MM-DD"
 *   {{location}} → session.sceneCard.location (empty string when unset)
 *   {{weather}}  → session.sceneCard.weather  (empty string when unset)
 *
 * Unknown macros are left intact so they surface as bugs rather than
 * silently vanishing. Matching is case-insensitive for the token name.
 *
 * Safe for prompt assembly AND user-visible text (opening-line preview,
 * chat bubble render). No HTML escaping here — callers that emit into
 * HTML must escape separately (same policy as plain user input).
 */

export interface MacroContext {
  character: { name: string };
  /** User's displayName on their account. Fallback when no persona. */
  userDisplayName?: string;
  /** Active persona name (G1a). Null / empty → falls back to userDisplayName. */
  personaName?: string | null;
  /** Scene card location (G6). */
  location?: string | null;
  /** Scene card weather (G6). */
  weather?: string | null;
  /**
   * Optional clock override — primarily for tests and replay. When omitted
   * we use `new Date()` at resolve time.
   */
  now?: Date;
  /**
   * IANA zone name (e.g. "Asia/Tokyo") for {{time}} / {{date}}. When
   * omitted the system local zone is used — this keeps test determinism
   * intact because callers supply `now` + `timezone` in fixtures.
   */
  timezone?: string;
}

const MACRO_RE = /\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/g;

function formatClock(date: Date, timezone?: string): { date: string; time: string } {
  const opts: Intl.DateTimeFormatOptions = timezone ? { timeZone: timezone } : {};
  const d = new Intl.DateTimeFormat('en-CA', {
    ...opts,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date);
  const t = new Intl.DateTimeFormat('en-GB', {
    ...opts,
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  }).format(date);
  return { date: d, time: t };
}

function lookup(ctx: MacroContext, tokenRaw: string): string | null {
  const token = tokenRaw.toLowerCase();
  switch (token) {
    case 'char':
      return ctx.character.name;
    case 'user':
      return ctx.personaName?.trim() || ctx.userDisplayName || '';
    case 'persona':
      return ctx.personaName?.trim() || '';
    case 'location':
      return ctx.location ?? '';
    case 'weather':
      return ctx.weather ?? '';
    case 'time':
    case 'date': {
      const clock = formatClock(ctx.now ?? new Date(), ctx.timezone);
      return token === 'time' ? clock.time : clock.date;
    }
    default:
      return null;
  }
}

/**
 * Resolve `{{...}}` macros in `text` against `ctx`. Unknown macros are left
 * verbatim (returns the original token untouched) so bugs surface.
 */
export function resolveMacros(text: string, ctx: MacroContext): string {
  if (!text || !text.includes('{{')) return text;
  return text.replace(MACRO_RE, (match, tokenRaw: string) => {
    const value = lookup(ctx, tokenRaw);
    return value === null ? match : value;
  });
}

/** List of macro tokens understood by the resolver. Stable for UI help. */
export const MACRO_TOKENS = [
  'char',
  'user',
  'persona',
  'time',
  'date',
  'location',
  'weather',
] as const;

export type MacroToken = (typeof MACRO_TOKENS)[number];

// ─────────────────────────────────────────────────────────────────────
// PLANv3 X2.3 — Advanced CBS macros (setvar/getvar/if/calc/comment/br)
// ─────────────────────────────────────────────────────────────────────

export type MacroMode = 'resolve' | 'tokenize' | 'display';

export interface MacroContextAdvanced extends MacroContext {
  /**
   * Mutable script-state bag. `{{setvar::k::v}}` mutates this in place so
   * callers can diff and persist changes. Empty object when caller doesn't
   * care about persistence.
   */
  scriptstate: Record<string, string>;
  /**
   * Trust boundary. TRUE for system prompt / character card / preset /
   * trigger output; FALSE for user-supplied text. Untrusted inputs have
   * `{{setvar}}` silently stripped so a crafted message can't overwrite
   * trust scores or mood variables.
   */
  trusted: boolean;
  /** Runaway block guard. Default 20. */
  maxDepth?: number;
}

export interface MacroResult {
  text: string;
  scriptstate: Record<string, string>;
  errors: string[];
}

/** Strings generated by `{{setvar}}` / `{{comment}}` / `{{//}}` evaluation. */
const CONTROL_REMOVED = '';

/**
 * Extended resolver supporting:
 *   {{getvar::k}}, {{setvar::k::v}}, {{if cond}}…{{/if}},
 *   {{calc::expr}}, {{comment}}…{{/comment}}, {{//}}, {{br}}
 *
 * Plus every simple token from `resolveMacros`. Leaves unknown macros
 * intact. Stack depth capped by `ctx.maxDepth` (default 20).
 *
 * Mode semantics:
 *   - `resolve`  (default) — full execute, setvar mutates state, comments stripped.
 *   - `tokenize` — no state mutation (pure preview); comments stripped.
 *   - `display`  — strip control ({{setvar}}, {{//}}, {{br}} → `\n`),
 *                   render {{getvar}} value, KEEP comment body visible.
 */
export function resolveMacrosEx(
  text: string,
  ctx: MacroContextAdvanced,
  mode: MacroMode = 'resolve',
): MacroResult {
  const errors: string[] = [];
  const maxDepth = ctx.maxDepth ?? 20;
  if (!text || !text.includes('{{')) {
    return { text: text ?? '', scriptstate: ctx.scriptstate, errors };
  }

  // Tokenize with nested-brace awareness so `{{if {{getvar::k}} == "x"}}`
  // captures the whole head.
  type Tok = { kind: 'text'; value: string } | { kind: 'macro'; raw: string };
  const toks: Tok[] = [];
  {
    let i = 0;
    let textStart = 0;
    while (i < text.length) {
      if (text[i] === '{' && text[i + 1] === '{') {
        if (i > textStart) toks.push({ kind: 'text', value: text.slice(textStart, i) });
        let depth = 1;
        let j = i + 2;
        while (j < text.length - 1 && depth > 0) {
          if (text[j] === '{' && text[j + 1] === '{') {
            depth++;
            j += 2;
            continue;
          }
          if (text[j] === '}' && text[j + 1] === '}') {
            depth--;
            if (depth === 0) break;
            j += 2;
            continue;
          }
          j++;
        }
        if (depth !== 0) {
          // Unbalanced — flush remainder as text.
          toks.push({ kind: 'text', value: text.slice(i) });
          textStart = text.length;
          break;
        }
        toks.push({ kind: 'macro', raw: text.slice(i + 2, j).trim() });
        i = j + 2;
        textStart = i;
        continue;
      }
      i++;
    }
    if (textStart < text.length) toks.push({ kind: 'text', value: text.slice(textStart) });
  }

  // Parse into an AST with block nodes ({{if}}/{{comment}}) using a stack.
  type Node =
    | { kind: 'text'; value: string }
    | { kind: 'simple'; name: string; args: string[] }
    | { kind: 'block'; name: string; condRaw?: string; body: Node[] };

  interface Frame {
    name: string;
    condRaw?: string;
    body: Node[];
  }
  const root: Node[] = [];
  const stack: Frame[] = [];
  const pushNode = (n: Node) => {
    if (stack.length) stack[stack.length - 1]!.body.push(n);
    else root.push(n);
  };

  for (const t of toks) {
    if (t.kind === 'text') {
      pushNode({ kind: 'text', value: t.value });
      continue;
    }
    const raw = t.raw;
    // Close tag {{/name}} — only treat as block-close when name is a known
    // block keyword, so that `{{//}}` (silent comment) stays a simple token.
    if (raw.startsWith('/')) {
      const closeName = raw.slice(1).trim().toLowerCase();
      if (closeName === 'if' || closeName === 'comment' || closeName === 'each') {
        const top = stack[stack.length - 1];
        if (!top || top.name !== closeName) {
          errors.push(`unmatched_close:${closeName}`);
          pushNode({ kind: 'text', value: `{{${raw}}}` });
          continue;
        }
        const frame = stack.pop()!;
        pushNode({ kind: 'block', name: frame.name, condRaw: frame.condRaw, body: frame.body });
        continue;
      }
      // fall through — treat as simple macro (e.g. `{{//}}`).
    }
    // Block-open: {{comment}} or {{if <cond>}}. Check raw BEFORE splitting
    // on '::' so cond strings with '::' survive (e.g. `{{getvar::k}}`).
    if (/^comment\s*$/i.test(raw)) {
      if (stack.length >= maxDepth) {
        errors.push('depth_limit_exceeded');
        pushNode({ kind: 'text', value: `{{${raw}}}` });
        continue;
      }
      stack.push({ name: 'comment', body: [] });
      continue;
    }
    const ifMatch = /^if\s+([\s\S]+)$/i.exec(raw);
    if (ifMatch) {
      if (stack.length >= maxDepth) {
        errors.push('depth_limit_exceeded');
        pushNode({ kind: 'text', value: `{{${raw}}}` });
        continue;
      }
      stack.push({ name: 'if', condRaw: ifMatch[1]!.trim(), body: [] });
      continue;
    }
    // Simple macro: split on `::` into head + args.
    const parts = raw.split('::');
    const name = parts[0]!.trim().toLowerCase();
    const args = parts.slice(1);
    pushNode({ kind: 'simple', name, args });
  }
  // Unterminated blocks → flush as literals and report.
  while (stack.length) {
    const frame = stack.pop()!;
    errors.push(`unterminated_block:${frame.name}`);
    // Recover by pushing body contents in order.
    for (const n of frame.body) pushNode(n);
  }

  // Evaluate AST.
  const out = evalNodes(root, ctx, mode, errors);
  return { text: out, scriptstate: ctx.scriptstate, errors };
}

function evalNodes(
  nodes: Array<
    | { kind: 'text'; value: string }
    | { kind: 'simple'; name: string; args: string[] }
    | { kind: 'block'; name: string; condRaw?: string; body: unknown[] }
  >,
  ctx: MacroContextAdvanced,
  mode: MacroMode,
  errors: string[],
): string {
  let out = '';
  for (const n of nodes) {
    if (n.kind === 'text') {
      out += n.value;
    } else if (n.kind === 'simple') {
      out += evalSimple(n.name, n.args, ctx, mode, errors);
    } else if (n.kind === 'block') {
      if (n.name === 'comment') {
        if (mode === 'display') {
          out += evalNodes(n.body as never, ctx, mode, errors);
        }
        // resolve/tokenize → drop.
      } else if (n.name === 'if') {
        const condValue = evalNodes(n.body as never, ctx, mode, errors);
        // First resolve nested macros in cond, then evaluate boolean.
        const condResolvedInner = resolveInlineSimpleTokens(n.condRaw ?? '', ctx, errors);
        if (evalCondition(condResolvedInner, errors)) {
          out += condValue;
        }
      }
    }
  }
  return out;
}

function evalSimple(
  name: string,
  args: string[],
  ctx: MacroContextAdvanced,
  mode: MacroMode,
  errors: string[],
): string {
  switch (name) {
    case 'getvar': {
      const k = args[0]?.trim();
      if (!k) return '';
      return ctx.scriptstate[k] ?? '';
    }
    case 'setvar': {
      const k = args[0]?.trim();
      const v = args.slice(1).join('::'); // allow '::' inside value
      if (!k) {
        errors.push('setvar_missing_key');
        return '';
      }
      if (!ctx.trusted) return CONTROL_REMOVED; // anti-injection
      if (mode === 'tokenize' || mode === 'display') return CONTROL_REMOVED;
      ctx.scriptstate[k] = v ?? '';
      return CONTROL_REMOVED;
    }
    case 'calc': {
      const expr = args.join('::');
      try {
        const n = evalArith(expr, errors);
        return Number.isFinite(n) ? String(n) : '';
      } catch (err) {
        errors.push(`calc_error:${String(err).slice(0, 40)}`);
        return '';
      }
    }
    case 'br':
      return '\n';
    case '//':
      return CONTROL_REMOVED;
    default: {
      // Fallback to legacy simple-token lookup (char/user/persona/time/etc).
      const v = lookup(ctx, name);
      if (v !== null) return v;
      // Unknown — leave literal so bugs surface.
      const argPart = args.length ? '::' + args.join('::') : '';
      return `{{${name}${argPart}}}`;
    }
  }
}

/**
 * Resolve only simple single-line tokens inside a condition string so that
 * `{{if {{getvar::mood}} == "happy"}}` becomes `"happy" == "happy"` before
 * boolean evaluation. Does NOT honour nested blocks (cond is one line).
 */
function resolveInlineSimpleTokens(
  text: string,
  ctx: MacroContextAdvanced,
  errors: string[],
): string {
  return text.replace(/\{\{([^{}]+?)\}\}/g, (_m, raw: string) => {
    const [headRaw, ...rest] = raw.trim().split('::');
    const name = headRaw!.trim().toLowerCase();
    const v = evalSimple(name, rest, ctx, 'resolve', errors);
    // Quote non-numeric results so they are valid string literals for the
    // arithmetic grammar. `{{getvar::mood}}`→`"happy"` not bare `happy`.
    if (/^-?\d+(\.\d+)?$/.test(v)) return v;
    return JSON.stringify(v);
  });
}

/**
 * Safe arithmetic evaluator. Supports:
 *   - literals: integers, decimals, "string" / 'string'
 *   - operators: + - * / % ( )
 *   - comparison: == != < <= > >= (boolean → 1/0 for calc; boolean for cond)
 *   - logical:   && ||
 * Rejects identifiers, function calls, bracket access, dots. No eval(),
 * no Function(), no mathjs — hand-rolled shunting-yard.
 */
function evalArith(expr: string, errors: string[]): number {
  const v = evalExpression(expr, errors);
  if (typeof v === 'boolean') return v ? 1 : 0;
  if (typeof v === 'number') return v;
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

function evalCondition(expr: string, errors: string[]): boolean {
  try {
    const v = evalExpression(expr, errors);
    if (typeof v === 'boolean') return v;
    if (typeof v === 'number') return v !== 0;
    return Boolean(String(v).trim());
  } catch {
    return false;
  }
}

type Val = number | string | boolean;

const TOK_RE = /\s*(?:(\d+(?:\.\d+)?)|"([^"]*)"|'([^']*)'|(==|!=|<=|>=|&&|\|\||[+\-*/%<>()]))/g;

function tokenize(expr: string, errors: string[]): Array<{ t: 'num' | 'str' | 'op'; v: string }> {
  const out: Array<{ t: 'num' | 'str' | 'op'; v: string }> = [];
  let idx = 0;
  TOK_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = TOK_RE.exec(expr)) !== null) {
    if (m.index !== idx) {
      errors.push(`arith_reject:${expr.slice(idx, m.index).slice(0, 16)}`);
      throw new Error('disallowed token');
    }
    if (m[1] != null) out.push({ t: 'num', v: m[1] });
    else if (m[2] != null) out.push({ t: 'str', v: m[2] });
    else if (m[3] != null) out.push({ t: 'str', v: m[3] });
    else if (m[4] != null) out.push({ t: 'op', v: m[4] });
    idx = TOK_RE.lastIndex;
  }
  if (idx < expr.length && expr.slice(idx).trim().length > 0) {
    errors.push(`arith_reject:${expr.slice(idx).slice(0, 16)}`);
    throw new Error('trailing garbage');
  }
  return out;
}

function evalExpression(expr: string, errors: string[]): Val {
  const toks = tokenize(expr, errors);
  // Shunting-yard → RPN.
  const prec: Record<string, number> = {
    '||': 1,
    '&&': 2,
    '==': 3,
    '!=': 3,
    '<': 4,
    '<=': 4,
    '>': 4,
    '>=': 4,
    '+': 5,
    '-': 5,
    '*': 6,
    '/': 6,
    '%': 6,
  };
  const out: Array<{ t: 'num' | 'str' | 'op'; v: string }> = [];
  const ops: string[] = [];
  for (const tk of toks) {
    if (tk.t === 'num' || tk.t === 'str') out.push(tk);
    else if (tk.v === '(') ops.push('(');
    else if (tk.v === ')') {
      while (ops.length && ops[ops.length - 1] !== '(') out.push({ t: 'op', v: ops.pop()! });
      if (!ops.length) {
        errors.push('arith_unbalanced_paren');
        throw new Error('unbalanced');
      }
      ops.pop();
    } else {
      while (ops.length && ops[ops.length - 1] !== '(' && (prec[ops[ops.length - 1]!] ?? 0) >= (prec[tk.v] ?? 0)) {
        out.push({ t: 'op', v: ops.pop()! });
      }
      ops.push(tk.v);
    }
  }
  while (ops.length) {
    const op = ops.pop()!;
    if (op === '(') {
      errors.push('arith_unbalanced_paren');
      throw new Error('unbalanced');
    }
    out.push({ t: 'op', v: op });
  }
  // Evaluate RPN.
  const stack: Val[] = [];
  for (const tk of out) {
    if (tk.t === 'num') stack.push(Number(tk.v));
    else if (tk.t === 'str') stack.push(tk.v);
    else {
      const b = stack.pop();
      const a = stack.pop();
      if (a === undefined || b === undefined) {
        errors.push('arith_operand_missing');
        throw new Error('operand');
      }
      stack.push(applyOp(tk.v, a, b));
    }
  }
  const r = stack[0];
  return r === undefined ? 0 : r;
}

function applyOp(op: string, a: Val, b: Val): Val {
  switch (op) {
    case '+':
      return typeof a === 'string' || typeof b === 'string' ? String(a) + String(b) : Number(a) + Number(b);
    case '-':
      return Number(a) - Number(b);
    case '*':
      return Number(a) * Number(b);
    case '/':
      return Number(b) === 0 ? 0 : Number(a) / Number(b);
    case '%':
      return Number(b) === 0 ? 0 : Number(a) % Number(b);
    case '==':
      return a === b || String(a) === String(b);
    case '!=':
      return a !== b && String(a) !== String(b);
    case '<':
      return Number(a) < Number(b);
    case '<=':
      return Number(a) <= Number(b);
    case '>':
      return Number(a) > Number(b);
    case '>=':
      return Number(a) >= Number(b);
    case '&&':
      return toBool(a) && toBool(b);
    case '||':
      return toBool(a) || toBool(b);
    default:
      return 0;
  }
}

function toBool(v: Val): boolean {
  if (typeof v === 'boolean') return v;
  if (typeof v === 'number') return v !== 0;
  return Boolean(v.trim());
}

